- name: Deploy to AWS EC2
  env:
    PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
    INSTANCE_IP: ${{ secrets.AWS_INSTANCE_IP }}
  run: |
    echo "$PRIVATE_KEY" > aws_key.pem  
    chmod 600 aws_key.pem  
    mkdir -p ~/.ssh  
    ssh-keyscan -H $INSTANCE_IP >> ~/.ssh/known_hosts  
    ssh -i aws_key.pem ubuntu@$INSTANCE_IP << 'EOF'  
      # Ensure user has permissions for Docker commands  
      sudo usermod -aG docker ubuntu  
    
      # Define a unique container name
      CONTAINER_NAME="my-container-$(date +%s)"
    
      # Find and remove any existing container using the port
      CONTAINER_ID=$(sudo docker ps -q -f "publish=9090")
      if [ -n "$CONTAINER_ID" ]; then  
        echo "Stopping and removing old container..."
        sudo docker stop $CONTAINER_ID  
        sudo docker rm $CONTAINER_ID  
      fi  
    
      # Pull the latest image
      sudo docker pull solomon11/devops:latest  
    
      # Run the new container with a unique name
      echo "Running new container with name $CONTAINER_NAME..."
      sudo docker run -d --name $CONTAINER_NAME -p 9090:8081 solomon11/devops:latest  
    EOF
