name: Deploy Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Restore Maven Package
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('/*.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t solomon11/classwork:latest .

      - name: Push Docker image to Docker Hub
        run: docker push solomon11/classwork:latest

      - name: Deploy to AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          INSTANCE_IP: ${{ secrets.AWS_INSTANCE_IP }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: |
          echo "$PRIVATE_KEY" > aws_key.pem
          chmod 600 aws_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H $INSTANCE_IP >> ~/.ssh/known_hosts
          ssh -i aws_key.pem ubuntu@$INSTANCE_IP << 'EOF'
            # Export the environment variables
            export DATABASE_URL=${DATABASE_URL}
            export DATABASE_USERNAME=${DATABASE_USERNAME}
            export DATABASE_PASSWORD=${DATABASE_PASSWORD}

            # Pull the latest Docker image
            sudo docker pull solomon11/classwork:latest

            # Run Docker container with environment variables
            sudo docker run -d \
              -e DATABASE_URL=${DATABASE_URL} \
              -e DATABASE_USERNAME=${DATABASE_USERNAME} \
              -e DATABASE_PASSWORD=${DATABASE_PASSWORD} \
              -p 9090:9090 solomon11/classwork:latest
          EOF
